#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/bin/run.bspwm &

bspc monitor DP-1 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8
bspc monitor DP-2 -s DP-1	

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

